development:
  bucket: LearnTo-dev
  access_key_id: AKIAJMRGW7JB4EKDMTHA
  secret_access_key: 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
test:
  bucket: LearnTo-test
  access_key_id: AKIAJMRGW7JB4EKDMTHA
  secret_access_key: 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
production:
  bucket: LearnTo-prod
  access_key_id: AKIAJMRGW7JB4EKDMTHA
  secret_access_key: 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
